### ISSUE TITLE
add option to filter by record with WIS2-topic to subscribe to

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-gdc#11]
context: WMO is developing a WIS2 subscription manager to allow users to query the GDC and find topics to subscribe to on a Global Broker.
problem: currently when querying the GDC-API we find many datasets where we fail to parse a channel from the actional links and we need to parse many records before finding a dataset that can be subscribed to.

**Since subscribing to data notifications over MQTT via a Global Broker is a core feature of WIS2, I'd like to request for the GDC-API to provide the option to filter by records with a valid WIS2-topic to subscribe to.**

**Comment by tomkralidis** [comment]
A user can query by topic (partial or otherwise) as follows:

https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items?q=%22cache/a/wis2/bz-nms%22

Note that topic validation per se is not performed in the above as part of the search.
