### ISSUE TITLE
querying the GDC-API returns no results for q=GRIB but it does return results for q=GRIB2

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-gdc#12]
Currently the GDC-API returns no results for q=GRIB but it does return results for q=GRIB2

**Comment by tomkralidis** [comment]
wis2-gdc is evaluating term searches (i.e. GRIB2 exists, GRIB does not).  You could also use `q=GRIB*` as a wildcard option to `q`.

**Comment by maaikelimper** [comment]
Hi Tom you said "GRIB2 exists, GRIB does not" but the issue I reported is the opposite: 

https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items?q=GRIB
https://wis2-gdc.weather.gc.ca/collections/wis2-discovery-metadata/items?q=GRIB2

first call returns nothing, second returns results !

 Is it because q= requires more than 4 chars ?

**Comment by tomkralidis** [comment]
As discussed with @maaikelimper, the user/client could also "mask" a `q=` search with a wildcard, so that `q=GRIB` is sent to the wis2-gdc backend as `q=*GRIB*`.
