### ISSUE TITLE
Different GDC return different channels for the same record

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-gdc#13]
context: WMO is developing a WIS2 subscription manager to allow users to query the GDC and find topics to subscribe to on a Global Broker
problem: when performing the same query on GDC-Canada and GDC-China there are cases where the user ends up with a subscription to a different topic. For example Zambia returns topic starting with cache/a/wis2 for GDC-Canada but GDC-China returns topic starting with origin/a/wis2

Using Canada:
![image](https://github.com/wmo-im/wis2-gdc/assets/19169339/b73d7173-8c7b-4fb7-9a04-9015ca3f29d3)
![image](https://github.com/wmo-im/wis2-gdc/assets/19169339/eecc6f88-2910-409a-ac8a-c0141a2f5201)

Using China:
![image](https://github.com/wmo-im/wis2-gdc/assets/19169339/4dfea8ec-b250-47ab-94c4-a84310dd2bdb)
![image](https://github.com/wmo-im/wis2-gdc/assets/19169339/39dc204b-4583-4d7e-8eb7-faefb0dc7b5e)

**Comment by tomkralidis** [comment]
Mentioned in the [WIS2 Guide](https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_2_7_5_1_technical_considerations):

> A Global Discovery Catalogue will only update discovery metadata records to replace links for dataset subscription and notification (origin) with their equivalent links for subscription at Global Broker instances (cache).

This issue is better addressed between the WIS2 GDC operators (who are using various implementations and not necessarily wis2-gdc specific).
