### ISSUE TITLE
Separate build - Elasticsearch/wis2-gdc-backend

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-gdc#17]
To avoid the loss of metadata after a build, it would be good if you could address the containers individually in the makefile. Then all other containers could be rebuilt without having to re-register the metadata. Or would there then be problems with intercontainer communication after a partial build?

**Comment by tomkralidis** [comment]
@antje-s @nbuttdwd FYI PR in #18 for review and comment.  With PR #18, the backend is never re-initialized (only initialized if not exists) on startup.  I've also add a command and make directive to explicitly reinitialize the backend if needed, without needing to restart the entire system.
