### ISSUE TITLE
Search for Metadata of an Organisation

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-gdc#25]
It is currently possible to initiate a full-text search using the q parameter ("The optional q parameter supports keyword searching. Only records whose text fields contain one or more of the specified search terms are selected. The specific set of text keys/fields/properties of a record to which the q operator is applied is up to the description of the server. "), e.g. 

[https://wis2.dwd.de/gdc/collections/wis2-discovery-metadata/items?q=%22Government%20of%20Canada;%20Environment%20and%20Climate%20Change%20Canada;%20Meteorological%20Service%20of%20Canada%22](url)

OR
[https://wis2.dwd.de/gdc/collections/wis2-discovery-metadata/items?q=%22Deutscher%20Wetterdienst%22](url)

But is it ensured that the search string is used as a complete string by using the inverted commas? Currently, in the wis2-gdc implementation, the properties.contacts.organization field also seems to be indexed and used, but how can you query which fields are searched via q-parameter?

This use case probably occurs more frequently and a specific search only on the properties.contacts.organisation field (e.g. as query "term") could be useful. Or perhaps it is sufficient to request that this field is included for q parameter.

**Comment by antje-s** [comment]
The queryables /collections/wis2-discovery-metadata/queryables might be the fields searched by q parameter. Then the match for the example could be in description. A specific search for organization field would be useful in my opinion.

**Comment by antje-s** [comment]
One possibility seems to be a search via e.g. 
https://wis2.dwd.de/gdc/collections/wis2-discovery-metadata/items?f=json&q=((properties.contacts.organization:%22Direction+Generale+de+la+M%C3%A9t%C3%A9orologie%22)) 
Does such a search ensure that no search hits in other fields are also returned? From my point of view it should be like this. If yes, we could close this issue

**Comment by kaiwirt** [comment]
Can this issue be closed? See above comment from Antje

**Comment by tomkralidis** [comment]
> One possibility seems to be a search via e.g. https://wis2.dwd.de/gdc/collections/wis2-discovery-metadata/items?f=json&q=((properties.contacts.organization:%22Direction+Generale+de+la+M%C3%A9t%C3%A9orologie%22)) Does such a search ensure that no search hits in other fields are also returned? From my point of view it should be like this. If yes, we could close this issue

Nice job @antje-s.  Yes, in the above case we are leveraging the "known" wis2-gdc backend of Elasticsearch syntax.

Another option is using a nested property query per below (which I would say is "safer" in a pure GDC / OGC API - Record sense):

https://wis2.dwd.de/gdc/collections/wis2-discovery-metadata/items?f=json&contacts.organization=Direction+Generale%20de%20la%20M%C3%A9t%C3%A9orologie

(Note I've added this an example to the [WIS2 Cookbook](https://wmo-im.github.io/wis2-cookbook/cookbook/wis2-cookbook-DRAFT.html#_equality_queries)).

Having said this, in OGC API - Records we do not have any strict semantics of the `q` parameter (other than a CSV list of terms).
